version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/London"
      WEBPASSWORD: "${DOCKER_PASSWORD:-password}"
      PIHOLE_DNS_: 127.0.0.1;1.1.1.1;8.8.8.8;8.8.4.4
      WEBTHEME: "default-dark"
    volumes:
      - "etc-pihole/:/etc/pihole/"
      - "etc-dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    # https://github.com/docker/for-linux/issues/679
    healthcheck:
      disable: true

volumes:
  etc-pihole:
  etc-dnsmasq.d:
